# Generated by Django 5.0.3 on 2024-03-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_data", models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
