# Generated by Django 5.0.3 on 2024-03-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aes", "0003_product_delete_encrypteddata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="marja",
            new_name="margin",
        ),
        migrations.AddField(
            model_name="product",
            name="encrypted_margin",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="encrypted_package_code",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="encrypted_price",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
