# Generated by Django 5.0.3 on 2024-03-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vacancy",
            options={"verbose_name_plural": "Vacancies"},
        ),
        migrations.RenameField(
            model_name="vacancy",
            old_name="description",
            new_name="desc",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="salary_currency",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="salary_from",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="salary_to",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="title",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="position",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vacancy",
            name="salary",
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
